### ISSUE TITLE
support admin configuration

### ISSUE THREAD

**Issue by siggy** [BuoyantIO/linkerd#16]
The admin server should be configurable via linkerd's configuration file.  I.e something like:

``` yaml
admin:
  port: 9991
  ip: any
  superCoolExperimentalAdminFeature: true

routers:
- ...
```

The admin server should be initialized with a Linker's config state (including)

This probably necessitates moving away from TwitterServer's provided `admin` service and instantiating our own (reusing as much as possible from TwitterServer).

An `admin` field be added to the `Linker` trait, probably accompanied by a `withAdmin` helper.  The admin configuration should be parsed after all `routers` have been parsed so that it may be configured against the routers.
