### ISSUE TITLE
linkerd client cache contains stale namerd resolutions

### ISSUE THREAD

**Issue by klingerf** [BuoyantIO/linkerd#292]
There appears to be an issue with linkerd not properly invalidating its cache, after resolving a destination through namerd.  I'm seeing the issue with the filesystem namer, and @siggy is seeing it with the marathon namer.

Here's my linkerd config file:

```
routers:
- protocol: http
  label: incoming
  interpreter:
    kind: io.l5d.namerd
    dst: /$/inet/127.1/4100
    namespace: incoming
  servers:
  - port: 4141
    ip: 0.0.0.0
```

And my namerd config file:

```
admin:
  port: 9001
storage:
  kind: io.buoyant.namerd.storage.inMemory
  namespaces:
    incoming: |
      /srv        => /io.l5d.fs;
      /host       => /srv;
      /method     => /$/io.buoyant.http.anyMethodPfx/host;
      /http/1.1   => /method;
      /host/books => /srv/books-v2 | /srv/books;
namers:
- kind:    io.l5d.fs
  rootDir: disco
interfaces:
- kind: thriftNameInterpreter
  ip: 0.0.0.0
  port: 4100
- kind: httpController
  ip: 0.0.0.0
  port: 4180
```

In my use case, the "books" service is running on 7002 and the "books-v2" service is running on 7003.  My first request for books is successfully routed to books-v2 on 7003.  From the linkerd logs:

```
0414 23:44:19.468 df6a0929c5721b81.df6a0929c5721b81<:df6a0929c5721b81] BinaryAnnotation(namerd/client/bind/tree,/io.l5d.fs/books-v2)
0414 23:44:19.468 df6a0929c5721b81.df6a0929c5721b81<:df6a0929c5721b81] BinaryAnnotation(namerd/client/bind/ns,incoming)
0414 23:44:19.468 df6a0929c5721b81.df6a0929c5721b81<:df6a0929c5721b81] BinaryAnnotation(namerd/client/bind/path,/http/1.1/GET/books-v2)
```

Next I shutdown books v2 and remove it from service discovery.  The next request for books is successfully routed to books on 7002.  From the linkerd logs:

```
0414 23:53:52.861 d826fed747216185.d826fed747216185<:d826fed747216185] BinaryAnnotation(namerd/client/bind/tree,/io.l5d.fs/books)
0414 23:53:52.862 d826fed747216185.d826fed747216185<:d826fed747216185] BinaryAnnotation(namerd/client/bind/ns,incoming)
0414 23:53:52.862 d826fed747216185.d826fed747216185<:d826fed747216185] BinaryAnnotation(namerd/client/bind/path,/http/1.1/GET/books)
```

Next I restart the books-v2 service on port 7004 and re-add it to service discovery on that port.  My next request for books fails with a 503.  From the linkerd logs:

```
0414 23:59:29.005 f6375aca491a6898.f6375aca491a6898<:f6375aca491a6898] Rpc(incoming)
0414 23:59:29.005 f6375aca491a6898.f6375aca491a6898<:f6375aca491a6898] BinaryAnnotation(router.label,incoming)
0414 23:59:29.006 f6375aca491a6898.f6375aca491a6898<:f6375aca491a6898] BinaryAnnotation(namer.dtab.base,)
0414 23:59:29.006 f6375aca491a6898.f6375aca491a6898<:f6375aca491a6898] BinaryAnnotation(namer.dtab.local,)
0414 23:59:29.006 f6375aca491a6898.f6375aca491a6898<:f6375aca491a6898] BinaryAnnotation(namer.path,/http/1.1/GET/books)
0414 23:59:29.007 f6375aca491a6898.f6375aca491a6898<:f6375aca491a6898] Message(namer.success)
0414 23:59:29.007 f6375aca491a6898.f6375aca491a6898<:f6375aca491a6898] BinaryAnnotation(dst.id,/io.l5d.fs/books-v2)
0414 23:59:29.007 f6375aca491a6898.f6375aca491a6898<:f6375aca491a6898] BinaryAnnotation(dst.path,/)
D 0414 23:59:29.019 THREAD26: ChannelStatsHandler caught an exception
java.net.ConnectException: Connection refused: /127.0.0.1:7003
```

It doesn't re-resolve the service through namerd, and instead uses the cached 7003 address.

**Comment by siggy** [comment]
Similar behavior with marathon namer. Steps to repro:

1. deploy linkerd + namerd + books-v2 to dcos
2. successfully curl books-v2:

   ```bash
    curl -H "Host: books-v2" http://$PUBLIC_URL/books.json
   ```

3. remove books-v2 with:

    ```bash
    dcos marathon app remove /books-v2
    ```

4. curl books-v2, observe falling back to web with 404, as expected:

    ```bash
    curl -H "Host: books-v2" http://$PUBLIC_URL/books.json
    ```

5. redeploy books-v2 with:

    ```bash
    dcos marathon app add books-v2.json
    ```

6. `curl -H "Host: books-v2" http://$PUBLIC_URL/books.json` ... linkerd errors with:

    ```
    D 0414 22:22:18.750 THREAD26: ChannelStatsHandler caught an exception
    java.net.ConnectException: Connection refused: /10.0.1.66:29574
      at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
      at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
      at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152)
      at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
      at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
      at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
      at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
      at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
      at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
      at java.lang.Thread.run(Thread.java:745)
    ```

7. observe namerd returns a newer, correct address:

    ```bash
    $ curl $NAMERD_URL/api/1/bind/default/http/1.1/GET/books-v2
    /io.l5d.marathon/books-v2

    $ curl $NAMERD_URL/api/1/addr/default/io.l5d.marathon/books-v2
    Bound(Set(Inet(/10.0.1.66:12312,Map())),Map())
    Bound(Set(Inet(/10.0.1.66:12312,Map())),Map())
    ```

linkerd config
```yaml
admin:
  port: 9990
routers:
- protocol: http
  httpAccessLog: access.log
  identifier:
    kind: default
    httpUriInDst: true
  servers:
  - port: 4140
    ip: 0.0.0.0
  interpreter:
    kind: io.l5d.namerd
    dst: /$/inet/namerd-default.marathon.slave.mesos/4100
```

namerd config
```yaml
admin:
  port: 9001
storage:
  kind: io.buoyant.namerd.storage.experimental.zk
  hosts:
  - master.mesos:2181
  pathPrefix: /dtabs
  sessionTimeoutMs: 10000
namers:
- kind:   io.l5d.experimental.marathon
  prefix: /io.l5d.marathon
  host:   marathon.mesos
  port:   8080
  ttlMs:  10
interfaces:
- kind: thriftNameInterpreter
  ip: 0.0.0.0
  port: 4100
- kind: httpController
  ip: 0.0.0.0
  port: 4180
```

dtab:
```
/srv        => /io.l5d.marathon;
/www        => /srv/web;
/host       => /srv | /$/io.buoyant.http.anyHostPfx/www;
/method     => /$/io.buoyant.http.anyMethodPfx/host;
/http/1.1   => /method;
/http/1.0   => /$/io.buoyant.http.anyMethodPfx/www;
```
