### ISSUE TITLE
serversets namer and zk storage should accept addrs similarly

### ISSUE THREAD

**Issue by olix0r** [BuoyantIO/linkerd#299]
The zk dtab storage module and the serversets namer are incongruent:

```
storage:
  kind: io.buoyant.namerd.storage.experimental.zk
  hosts:
  - zk.example.com

namers:
- kind: io.l5d.serversets
  zkAddrs:
  - host: zk.example.com
    port: 2181
```

Either support `zkAddrs` or `hosts`, not both
