### ISSUE TITLE
LinkerD and NamerD processes should announce their presence.

### ISSUE THREAD

**Issue by zircote** [BuoyantIO/linkerd#628]
A running `linkerd` and/or `namerd` process should announce their admin interface using the various announcer plugins. This feature would therefore allow for such ancillary services as Prometheus to scrape metrics using such features as zookeeper server-set discovery to locate a 1:N deployment of each type. Its configuration may be defined within the `admin:` key of the instance itself.

Example:

```yaml
admin:
  port: 9990
  announcers:
    - type: io.l5d.serverset
      zkAddrs:
        - host: localhost
           port: 2181
      path: /disco/infra/prod/linkerd
```
