### ISSUE TITLE
Router TLS configuration

### ISSUE THREAD

**Issue by olix0r** [BuoyantIO/linkerd#63]
Once #21 is merged, we'll need a way to configure clientside TLS on the router.  I can think of at least 2 or 3 different configurations we'll want to support, so this should be modular (and perhaps pluggable, so that users may implement their own crazy policies).
##### Static validation

``` yaml
routers:
- protocol: http
  tls:
    kind: static
    name: buoyant.io
```
##### Per-service validation

``` yaml
routers:
- protocol: http
  baseDtab: /http/1.1/GET => /io.l5d.k8s/default/http
  tls:
    kind: boundPath
    certPath: /path/to/ca.pem
    matches:
    - prefix: /io.l5d.k8s
      name: ${3}.buoyant.io
```

The matchers should:
- extract the Name.Bound.id (we may want to explicitly put this on the stack rather than relying on BindingFactory.Dest).
- Path.read(Name.Bound.id)
- If a prefix matches:
  - strip the prefix
  - compute offsets in _name_ against the path post-prefix-stripping.  If the offset is out of range, the match should not apply
- if any of these steps fail or a match is not found, TLS should not be applied
- multiple matches should be able to specify overlapping prefixes

Parsing the `name` values may be slightly tricky, but we can probably write a parser-generator to do this.
##### No validation

``` yaml
routers:
- protocol: http
  baseDtab: /http/1.1/GET => /io.l5d.k8s/default/http
  tls:
    kind: noValidationYoloSwag
```

(And, yes, i think that's what that option should be called.)
##### Per-host validation

We can probably punt this down the road, but, we can use the IP or Hostname of the individual destination address as the peer's name.
