### ISSUE TITLE
Namerd with k8s storage does not return a correct dtab after update

### ISSUE THREAD

**Issue by OleksandrBerezianskyi** [BuoyantIO/linkerd#685]
Configuration is very similat to the one described in #627, but here we use 2 namerd instances:

``` yaml
apiVersion: v1
kind: Service
metadata:
  name: namerd-sync
spec:
  selector:
    app: namerd
  ports:
  - name: sync
    port: 4100
---
apiVersion: v1
kind: Service
metadata:
  name: namerd-api
spec:
  selector:
    app: namerd
  ports:
  - name: api
    port: 4180
---
metadata:
  name: d-tab.l5d.io # the hyphen is required by the Kubernetes API. This will be converted to the CamelCase name "DTab".
apiVersion: extensions/v1beta1
kind: ThirdPartyResource
description: stores dtabs used by Buoyant's `namerd` service
versions:
  - name: v1alpha1 # Do not change this value as it hardcoded in Namerd and doesn't work with other value.
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: namerd-config
data:
  config.yml: |-
    admin:
      port: 9991
    storage:
      kind: io.l5d.k8s
      experimental: true
    namers:
      - kind: io.l5d.k8s
        experimental: true
        host: 127.0.0.1
        port: 8001
    interfaces:
      - kind: io.l5d.thriftNameInterpreter
        ip: 0.0.0.0
        port: 4100
      - kind: io.l5d.httpController
        ip: 0.0.0.0
        port: 4180
---
kind: ReplicationController
apiVersion: v1
metadata:
  name: namerd
spec:
  replicas: 2
  selector:
    app: namerd
  template:
    metadata:
      labels:
        app: namerd
    spec:
      dnsPolicy: ClusterFirst
      volumes:
        - name: namerd-config
          configMap:
            name: namerd-config
      containers:
        - name: namerd
          image: buoyantio/namerd:0.7.4
          args:
            - /io.buoyant/namerd/config/config.yml
            - -com.twitter.finagle.tracing.debugTrace=true
            - -log.level=DEBUG
          imagePullPolicy: Always
          ports:
            - name: sync
              containerPort: 4100
            - name: api
              containerPort: 4180
          volumeMounts:
            - name: "namerd-config"
              mountPath: "/io.buoyant/namerd/config"
              readOnly: true
        - name: kubectl
          image: buoyantio/kubectl:1.2.3
          args:
          - "proxy"
          - "-p"
          - "8001"
          imagePullPolicy: Always
```

Now we have 2 pods running Namerd. Here is the result of executing some curl command using `docker exec` in the order of execution

1st pod: 
command: `curl http://127.0.0.1:4180/api/1/dtabs/stage`
result:

``` json
[{"prefix":"/srv","dst":"/#/io.l5d.k8s/stage/http"},{"prefix":"/host","dst":"/srv"},{"prefix":"/host/rss","dst":"/srv/rss"},{"prefix":"/http/1.1/*","dst":"/host"}]
```

2nd pod: 
command: `curl http://127.0.0.1:4180/api/1/dtabs/stage`
result:

``` json
[{"prefix":"/srv","dst":"/#/io.l5d.k8s/stage/http"},{"prefix":"/host","dst":"/srv"},{"prefix":"/host/rss","dst":"/srv/rss"},{"prefix":"/http/1.1/*","dst":"/host"}]
```

1st pod:
command: 

``` bash
cat > body.dtab << EOL        
/srv=>/#/io.l5d.k8s/stage/http;
/host=>/srv;
/host/rss=>/srv/bug;
/http/1.1/*=>/host
EOL
```

command: `curl -v -H "Content-Type: application/dtab" --data @body.dtab -X PUT http://127.0.0.1:4180/api/1/dtabs/stage`
command: `curl http://127.0.0.1:4180/api/1/dtabs/stage`
result:

``` json
[{"prefix":"/srv","dst":"/#/io.l5d.k8s/stage/http"},{"prefix":"/host","dst":"/srv"},{"prefix":"/host/rss","dst":"/srv/rss"},{"prefix":"/http/1.1/*","dst":"/host"}]
```

**please note that `"dst":"/srv/rss"` even though we have updated the dtab**

2nd pod: 
command: `curl http://127.0.0.1:4180/api/1/dtabs/stage`
result:

``` json
[{"prefix":"/srv","dst":"/#/io.l5d.k8s/stage/http"},{"prefix":"/host","dst":"/srv"},{"prefix":"/host/rss","dst":"/srv/bug"},{"prefix":"/http/1.1/*","dst":"/host"}]
```

**please note that in the second pod the value is correct: `"dst":"/srv/bug"`**

Please note that there is **rss** service existing in **stage** k8s namespace, but **bug** service does not exist.

For some reason I could not reproduce this behaviour in a synthetic namespace with just namerds and fake services.
