### ISSUE TITLE
ZKServerSet Announcer doesn't provide routable address

### ISSUE THREAD

**Issue by JustinVenus** [BuoyantIO/linkerd#748]
Host `0.0.0.0` isn't very useful to announce.  I took away the ip address and it publishes "localhost" :/ ... I'm not sure what else to configure here.

Znode info
```sh
[zk: mesos-master01of2:2181(CONNECTED) 22] get /sd/nobody/prod/linkerd/member_0000000004
{"serviceEndpoint":{"host":"0.0.0.0","port":4140},"additionalEndpoints":{},"status":"ALIVE","shard":0}
cZxid = 0x140000e6d7
ctime = Fri Oct 14 14:29:37 CDT 2016
mZxid = 0x140000e6d7
mtime = Fri Oct 14 14:29:37 CDT 2016
pZxid = 0x140000e6d7
cversion = 0
dataVersion = 0
aclVersion = 0
ephemeralOwner = 0x1578b3924500875
dataLength = 102
numChildren = 0
```

linkerd.yaml
```yaml
admin:
  port: 9990

namers:
- kind: io.l5d.serversets
  zkAddrs:
  - host: mesos-master01of2
    port: 2181
  - host: mesos-master02of2
    port: 2181
  - host: mesos-master03of2
    port: 2181

routers:
- protocol: http
  interpreter:
    kind: io.l5d.namerd
    dst: /#/io.l5d.serversets/sd/nobody/devel/namerd:thrift
    namespace: default
  announcers:
  - kind: io.l5d.serversets
    zkAddrs:
    - host: mesos-master01of2
      port: 2181
    - host: mesos-master02of2
      port: 2181
    - host: mesos-master03of2
      port: 2181
    pathPrefix: /sd/nobody
  responseClassifier:
    kind: io.l5d.retryableRead5XX
  servers:
  - port: 4140
    label: prod/linkerd
    ip: 0.0.0.0
    announce:
    - /#/io.l5d.serversets/prod/linkerd
```
