### ISSUE TITLE
Add "client" section to router configs

### ISSUE THREAD

**Issue by klingerf** [BuoyantIO/linkerd#75]
Once #73 ships, we'll have a few configuration options at the top level of our router config that are also available within the `servers` section of the same router config.  The options at the top level apply to clients that are dynamically created by the router, whereas the options in the `servers` section apply to servers that are created when the router starts.  For clarity, we should move the client-only top level options into a `client` config section.

Previously:

```
routers:
- protocol: thrift
  baseDtab: |
    /thrift => /io.l5d.fs/aservice;
  thriftFramed: false
  tls:
    kind: io.l5d.NoValidationTlsClient
  servers:
  - port: 4114
    ip: 0.0.0.0
    thriftFramed: false
    tls:
      certPath: /foo/cacert.pem
      keyPath: /foo/private/cakey.pem
```

Proposed future:

```
routers:
- protocol: thrift
  baseDtab: |
    /thrift => /io.l5d.fs/aservice;
  client:
    thriftFramed: false
    tls:
      kind: io.l5d.NoValidationTlsClient
  servers:
  - port: 4114
    ip: 0.0.0.0
    thriftFramed: false
    tls:
      certPath: /foo/cacert.pem
      keyPath: /foo/private/cakey.pem
```
