### ISSUE TITLE
Allow namers to accept a list of transformers

### ISSUE THREAD

**Issue by adleong** [BuoyantIO/linkerd#768]
Add support for namers to accept a list of transformer config blocks.

```
namers:
- kind: io.l5d.fs
   rootDir: linkerd/examples/io.l5d.fs
  transformers:
  - kind: io.l5d.localnode
```

This should apply the NameTree transformers to the output of the Namer.
