### ISSUE TITLE
h2 client does not reconnect

### ISSUE THREAD

**Issue by olix0r** [BuoyantIO/linkerd#785]
Repro:

Run linkerd with a config like:

``` yaml
- protocol: h2
  experimental: true
  baseDtab: |
    /h2/localhost:4142 => /$/inet/127.1/8888;
    /h2 => /srv;
  servers:
  - port: 4142
  identifier:
    kind: io.l5d.headerToken
    header: ":authority"
```

Run nghttpd

```
:; nghttpd --no-tls -v 8888                                                                                                              
IPv4: listen 0.0.0.0:8888
IPv6: listen :::8888
```

Perform request:

```
:; curl --http2 http://localhost:4142/
```

Kill nghttpd

Curl again (should fail)

Restart nghttpd

Curl again.  Should succeed, but fails with:

```
l5d-err: com.twitter.finagle.DroppedWriteException
```
