### ISSUE TITLE
dtab union with fail not working as expected

### ISSUE THREAD

**Issue by siggy** [BuoyantIO/linkerd#820]
#### union with bad service at 100% SR

given the following dtab:
```
/srv        => /#/io.l5d.marathon ;
/host       => /srv & /srv/badservice ;
/http/1.1/* => /host ;
```
expected: 50% SR
observed: 100% SR

#### ~~union with fail at 0% SR~~

given the following dtab:
```
/srv        => /#/io.l5d.marathon ;
/host       => /srv & /$/fail ;
/http/1.1/* => /host ;
```
expected: 50% SR
observed: 0% SR

#### ~~union with empty at 100% SR~~

given the following dtab:
```
/srv        => /#/io.l5d.marathon ;
/host       => /srv & /$/empty ;
/http/1.1/* => /host ;
```
expected: 50% SR
observed: 100% SR

#### curl from laptop to linkerd on DC/OS cluster
```bash
http_proxy=http://PUBLIC_DCOS_NODE:4140 curl webapp/hello
```
#### linkerd on DC/OS configured to talk to namerd in Helium
```json
{
  "routers": [
    {
      "protocol": "http",
      "servers": [
        {
          "port": 4140,
          "ip": "0.0.0.0"
        }
      ],
      "label": "linkerd_proxy",
      "interpreter": {
        "kind": "io.l5d.namerd",
        "dst": "/$/inet/helium-xxx.amazonaws.com/4100"
      }
    }
  ],
  "admin": {
    "port": 9990
  }
}
```

#### namerd in Helium configured to talk to Marathon namer in DC/OS:

```yaml
admin:
  port: 9001
storage:
  kind: io.l5d.zk
  experimental: true
  pathPrefix: /dtabs
  zkAddrs:
  - host: 10.1.0.5
    port: 2181
  - host: 10.1.0.6
    port: 2181
  - host: 10.1.0.4
    port: 2181
namers:
- kind: io.l5d.marathon
  experimental: true
  prefix: /io.l5d.marathon
  host: buoyant-c-ElasticL-xxx.us-west-1.elb.amazonaws.com
  port: 8080
  uriPrefix:
  ttlMs: 5000
  useHealthCheck: false
interfaces:
- kind: io.l5d.thriftNameInterpreter
  ip: 0.0.0.0
  port: 4100
- kind: io.l5d.httpController
  ip: 0.0.0.0
  port: 4180
```
